import { ActionButton as Button } from "../../infrastructure/components/ActionButton";
import {Card, Input, InputNumber, Select, Table} from "antd";
import type { ReactNode } from 'react';
import { ConfigurationField } from '../../infrastructure/components/ConfigurationField';
const labels:Record<string,string>={n_hidden:'隐藏层宽度',n_layers:'网络层数',n_head:'注意力头数',mlp_ratio:'前馈网络宽度倍率',slice_num:'切片数量',space_dim:'空间输入维度',fun_dim:'条件输入维度',out_dim:'预测输出维度',unified_pos:'统一位置编码',gradient_checkpointing:'梯度检查点',dim:'特征维度',depth:'网络深度',num_heads:'注意力头数',hidden_dim:'隐藏特征维度',num_blocks:'模块数量',seed:'随机种子',stride:'采样步长',chunk_count:'查询分块数',random_stream:'随机流',num_surface_inputs:'表面输入点数',num_surface_queries:'表面查询点数',num_volume_inputs:'体场输入点数',num_volume_queries:'体场查询点数',num_anchors:'锚点数量'};
/** 模型配置与真实结构并列，采样和学习目标拥有独立编辑区域。 */
export function ModelPanel({capabilities,values,onChange,trace,traceUrl,onTrace,busy,canTrace=true,bindings}:{capabilities?:any;values:any;onChange:(key:string,v:any)=>void;trace:any;traceUrl?:string;onTrace:()=>void;busy:boolean;canTrace?:boolean;bindings:ReactNode}){
 const losses=values.supervision||[];
 const sampling:any[]=[];function walk(value:any,path:string[]=[]){for(const [key,child]of Object.entries(value||{})){if(child&&typeof child==='object'&&!Array.isArray(child))walk(child,[...path,key]);else if(['string','number','boolean'].includes(typeof child))sampling.push({path:[...path,key],value:child})}}walk(values.sampling);
 return <div className="model-layout"><Card title="模型参数设置"><h3>模型选择与版本</h3><p>使用当前任务案例声明的正式模型；结构和参数规模以实际跟踪结果为准。</p>{bindings}<h3>主干参数</h3><div className="configuration-grid">{Object.entries(values.parameters||{}).filter(([,v])=>['number','string','boolean'].includes(typeof v)).map(([key,value])=><ConfigurationField key={key} label={labels[key]||key} help={key} value={value} onChange={v=>onChange('parameters',{...values.parameters,[key]:v})}/>)}</div><h3>输入输出绑定</h3>{Object.entries(values.data_specs?.domains||{}).map(([domain,definition])=><div key={domain}><b>{domain}</b>{Object.entries((definition as any).output_dims||{}).map(([field,dim])=><ConfigurationField key={field} label={field+' 输出维度'} value={dim} onChange={v=>onChange('data_specs',{...values.data_specs,domains:{...values.data_specs.domains,[domain]:{...values.data_specs.domains[domain],output_dims:{...values.data_specs.domains[domain].output_dims,[field]:v}}}})}/>)}</div>)}<h3>学习目标与损失</h3>{capabilities?.losses?.configurable===false?<p>固定等权 MSE · {capabilities.losses.reason}</p>:<Table<any> rowKey="name" pagination={false} dataSource={losses} columns={[{title:'目标字段',dataIndex:'target'},{title:'损失函数',render:(_,row)=><Select value={row.loss} options={['mse','mae','huber','relative_l2'].map(value=>({value,label:value}))} onChange={loss=>onChange('supervision',losses.map((v:any)=>v.name===row.name?{...v,loss}:v))}/>},{title:'权重',render:(_,row)=><InputNumber value={row.weight} min={0} onChange={weight=>onChange('supervision',losses.map((v:any)=>v.name===row.name?{...v,weight}:v))}/>} ]}/>}<h3>模型采样</h3><div className="sampling-grid">{sampling.map(row=><ConfigurationField key={row.path.join('.')} label={row.path.map((k:string)=>labels[k]||k).join(' / ')} help={'model.sampling.'+row.path.join('.')} value={row.value} onChange={v=>{const sample=structuredClone(values.sampling);let node=sample;row.path.slice(0,-1).forEach((k:string)=>node=node[k]);node[row.path.at(-1)]=v;onChange('sampling',sample)}}/>)}</div><h3>权重加载</h3><p>从检查点继续请进入训练运行；模型检查使用当前参数和真实准备输入。</p></Card><Card className="model-visualization" title="模型可视化" extra={<Button type="primary" loading={busy} disabled={!canTrace} onClick={onTrace}>生成真实模型结构</Button>}>{trace&&traceUrl?<><p>参数量 {trace.result.parameter_count?.toLocaleString()} · {trace.result.model_type}</p><iframe title="真实模型结构" sandbox="allow-scripts" src={traceUrl}/></>:<div className="empty-record">TorchVista 模型结构<br/><small>{canTrace?'选择准备输入后将跟踪实际模型':'请先选择物理数据清单或准备记录，再生成真实结构'}</small></div>}</Card></div>
}
