case: diffusion_trapezoid
dataset:
  name: diffusion_trapezoid
run_root: ../../../../../project_simulation/dojo_train/pibsnet/trapezoid_dojo_10/runs
trainprep:
  execute: true
train:
  execute: true
  device: cpu
post: {}
data_root: ../data
pipeline:
  stages:
  - rawprep
  - trainprep
  - train
  - infer
  - post
inputs:
  rawprep:
    manifest: ../../../../../project_simulation/dojo_train/pibsnet/trapezoid_dojo_10/datasets/manifest.json
  trainprep:
    dataset: ../../../../../project_simulation/dojo_train/pibsnet/trapezoid_dojo_10/datasets/manifest.json
  train:
    dataset: ../../../../../project_simulation/dojo_train/pibsnet/trapezoid_dojo_10/datasets/manifest.json
    preparation: null
    resume: null
  infer:
    dataset: ../../../../../project_simulation/dojo_train/pibsnet/trapezoid_dojo_10/datasets/manifest.json
    preparation: null
    checkpoint: null
  post:
    results: null
