import { Alert, Button, Empty, Input, Modal, Tooltip } from 'antd';
import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { list, save, projectTasks } from './api';
/** 原型项目卡片使用服务事实；封面仅为研究主题装饰，不表示计算结果。 */
export function ProjectNavigation() {
 const [params]=useSearchParams();
 const [rows,setRows]=useState<any[]>([]),[summaries,setSummaries]=useState<Record<string,any>>({}),[q,setQ]=useState(params.get('q')||''),[scope,setScope]=useState('all'),[domain,setDomain]=useState('all'),[sort,setSort]=useState('updated'),[editing,setEditing]=useState<any>(),[error,setError]=useState('');
 async function load(){try{const records=await list();setRows(records);const facts=await Promise.all(records.map(async(r:any)=>{try{const tasks=await projectTasks(r.id);const bases=[...new Set(tasks.map((t:any)=>t.baseline_version_id).filter(Boolean))];return[r.id,{count:tasks.length,baseline:bases.length===1?String(bases[0]).slice(0,8):bases.length>1?'多个基线':'未设置'}]}catch{return[r.id,{count:'读取失败',baseline:'—'}]}}));setSummaries(Object.fromEntries(facts))}catch(e:any){setError(e.message)}}
 useEffect(()=>{void load()},[]);useEffect(()=>setQ(params.get('q')||''),[params]);
 async function persist(v:any,id?:string){try{await save(v,id);setEditing(undefined);await load();setError('')}catch(e:any){setError(e.message)}}
 const displayed=rows.filter(r=>(r.name+' '+(r.description||'')).includes(q)&&(scope!=='archived'||r.archived)&&(domain==='all'||(r.domain||'未分类')===domain)).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'zh'):sort==='created'?String(a.created_at).localeCompare(String(b.created_at)):String(b.updated_at||b.created_at).localeCompare(String(a.updated_at||a.created_at)));
 const date=(v:string)=>v?new Date(v).toLocaleDateString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'}):'未记录';
 return <section className="project-navigation"><div className="page-heading heading"><div><h1>项目管理</h1><p>管理研究项目，追踪研究进展，沉淀研究成果</p></div></div>{error&&<Alert type="error" message={error}/>}
 <div className="projectbar"><nav className="scopetabs" aria-label="项目范围"><button className={scope==='all'?'active':''} onClick={()=>setScope('all')}>全部项目</button><Tooltip title="本机项目尚未记录负责人"><button disabled>我负责的</button></Tooltip><Tooltip title="本机项目尚未记录参与成员"><button disabled>我参与的</button></Tooltip><button className={scope==='archived'?'active':''} onClick={()=>setScope('archived')}>已归档</button></nav><input aria-label="搜索项目" placeholder="⌕　搜索项目名称或关键词…" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="筛选研究领域" value={domain} onChange={e=>setDomain(e.target.value)}><option value="all">全部领域</option>{[...new Set(rows.map(r=>r.domain||'未分类'))].map(value=><option key={value} value={value}>{value}</option>)}</select><select aria-label="项目排序" value={sort} onChange={e=>setSort(e.target.value)}><option value="updated">更新时间 ↓</option><option value="created">创建时间 ↑</option><option value="name">名称 A–Z</option></select><button className="primary" aria-label="新建项目" onClick={()=>setEditing({name:'',description:''})}>＋ 新建项目</button></div>
 <div className="projectcount" aria-live="polite"/><div className="project-grid projectgrid">{displayed.map((r,i)=><article className="project-card taskcard" key={r.id}><Link to={`/projects/${r.id}/tasks`} tabIndex={-1} aria-hidden="true"><img className="projectcover" src={`/project-covers/research-${i%4+1}.jpg`} alt=""/></Link><div className="cardbody"><h2><Link to={`/projects/${r.id}/tasks`}>{r.name}</Link></h2><p className="project-description">{r.description||'尚未填写项目描述'}</p><div className="projectfacts"><div><small>任务数</small><b>{summaries[r.id]?.count??'—'}</b></div><div><small>基线版本</small><b>{summaries[r.id]?.baseline??'—'}</b></div><div><small>更新时间</small><b>{date(r.updated_at||r.created_at)}</b></div><div><small>创建时间</small><b>{date(r.created_at)}</b></div></div><div className="cardfoot"><span className="project-avatar">{(r.owner||r.created_by||'研').slice(0,1)}</span><div className="project-owner"><b>{r.owner||r.created_by||'负责人未记录'}</b><small>{r.domain||'研究领域未分类'}</small></div><div className="card-actions"><Button type="text" onClick={()=>setEditing(r)}>编辑</Button><Button type="text" onClick={()=>persist({archived:!r.archived},r.id)}>{r.archived?'恢复':'归档'}</Button><Link className="enter-project" aria-label="进入项目" to={`/projects/${r.id}/tasks`}>进入项目 →</Link></div></div></div></article>)}</div>{!displayed.length&&<Empty description="没有符合条件的项目"/>}
 <Modal open={!!editing} title={editing?.id?'编辑项目':'新建项目'} onCancel={()=>setEditing(undefined)} onOk={()=>persist({name:editing.name,description:editing.description},editing.id)}><Input aria-label="项目名称" placeholder="项目名称" value={editing?.name} onChange={e=>setEditing({...editing,name:e.target.value})}/><Input.TextArea aria-label="项目描述" placeholder="项目描述" value={editing?.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></Modal></section>
}
