import { ActionButton as Button } from "../../infrastructure/components/ActionButton";
import {Alert, Select, Space, Spin} from "antd";
import {useEffect,useState} from 'react';
import {ExecutionLog,TrainingMonitor,listRuns} from '../executions';
import {PreparationPanel} from '../trainprep';
import {ModelPanel} from '../models';
import {TrainingPanel} from '../training';
import {PostWorkspace} from '../post';
import {readStage,saveStage,runStage,traceModel,stageInputs,modelAssetUrl} from './api';

/** 应用协调仅维护配置修订与交接，五个页面各自表达业务配置。 */
export function StageWorkbench({project,task,stage}:{project:string;task:string;stage:string}){
 const [cfg,setCfg]=useState<any>(),[values,setValues]=useState<any>(),[inputs,setInputs]=useState<any[]>([]),[bindings,setBindings]=useState<Record<string,any>>({}),[runs,setRuns]=useState<any[]>([]),[run,setRun]=useState<string>(),[trace,setTrace]=useState<any>(),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
 useEffect(()=>{let live=true;setCfg(undefined);setError('');setBindings({});setDirty(false);Promise.all([readStage(project,task,stage==='execution'?'train':stage),stageInputs(project,task),listRuns(project,task)]).then(([c,i,r])=>{if(!live)return;setCfg(c);setValues(c.values);setInputs(i);if(stage==='model'){const next:Record<string,any>={};for(const key of ['train.manifest','train.preparation']){const found=[...i].reverse().find((item:any)=>item.binding===key);if(found)next[key]=found.ref}setBindings(next)}const expected=stage==='execution'?'train':stage;const candidates=stage==='model'?[]:r.filter((x:any)=>(x.stages||Object.keys(x.summary?.reports||{})).includes(expected));setRuns(candidates);setRun([...candidates].sort((a,b)=>String(b.created_at||b.created||'').localeCompare(String(a.created_at||a.created||'')))[0]?.id)}).catch(e=>live&&setError(e.message));return()=>{live=false}},[project,task,stage]);
 function change(key:string,value:any){setValues((old:any)=>({...old,[key]:value}));setDirty(true);setMessage('')}
 async function action(mode:string){if(mode!=='save'&&dirty){setError('配置有修改，请先保存');return}setBusy(true);setError('');try{if(mode==='save'){const saved=await saveStage(project,task,cfg.stage,cfg.revision,values);setCfg({...cfg,revision:saved.revision});setDirty(false);setMessage('配置已保存，未创建新版本')}else if(mode==='trace'){setTrace(await traceModel(project,task,cfg.revision,bindings));setMessage('真实模型结构已生成')}else{const result=await runStage(project,task,cfg.stage,cfg.revision,mode,{prepare_first:stage==='execution',bindings});if(result.id){setRun(result.id);setRuns([...runs,result]);setMessage('运行已提交')}else setMessage(result.valid?'配置与交接检查通过':JSON.stringify(result));}}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(!cfg)return error?<Alert type="error" message={error}/>:<Spin/>;
 const bindingKeys=stage==='trainprep'?['train.manifest']:stage==='post'?['train.preparation','post.checkpoint']:['train.manifest','train.preparation'];
 const bindingPanel=<div className="input-bindings" id="stage-handoff">{bindingKeys.map(binding=><div key={binding}><label>{({'train.manifest':'物理数据清单','train.preparation':'准备记录','post.checkpoint':'模型检查点'}as any)[binding]}</label><Select allowClear aria-label={binding} style={{width:'100%',marginBottom:12}} placeholder="选择正式运行产物" value={bindings[binding]?.asset_id} options={inputs.filter(i=>i.binding===binding).map(i=>({value:i.ref.asset_id,label:i.run_id.slice(0,8)+' / '+i.name}))} onChange={value=>{const next={...bindings};if(value)next[binding]=inputs.find(i=>i.ref.asset_id===value).ref;else delete next[binding];setBindings(next)}}/></div>)}</div>;
 const titles:Record<string,string>={trainprep:"数据准备",model:"模型设置",train:"训练设置",execution:"训练运行",post:"后处理"};
 const intros:Record<string,string>={trainprep:"按当前任务已保存配置继续本阶段；检查、试跑与正式运行分开。",model:"按当前任务已保存配置继续本阶段；检查、试跑与正式运行分开。",train:"按当前任务已保存配置继续本阶段；检查、试跑与正式运行分开。",execution:"按当前任务已保存配置继续本阶段；检查、试跑与正式运行分开。",post:"在管线浏览器中选择结果，设置显示与过滤器；同时查看指标和图表。"};
 return <>{stage!=='trainprep'&&<div className={"stage-toolbar"+(stage==='post'?' post-stage-toolbar':'')}><div className="stageheading"><div><h2>{titles[stage]}</h2><p>{intros[stage]}</p></div></div><div className={stage==='post'?'post-stage-actions':undefined}><Space><Button onClick={()=>action('check')} loading={busy} disabled={dirty}>检查配置与交接</Button><Button type="primary" onClick={()=>action('save')} disabled={!dirty} loading={busy}>保存配置</Button></Space></div></div>}{cfg.capabilities?.unavailable_reason&&<Alert type="warning" message="能力检查暂不可用，仍可修改已保存配置" description={cfg.capabilities.unavailable_reason}/>} {error&&<Alert type="error" message={error}/>} {message&&<Alert type="success" message={message}/>}
 {stage==='trainprep'?<PreparationPanel project={project} task={task} values={values} onChange={change} bindings={bindingPanel} onExecute={()=>action('execute')} onCheck={()=>action('check')} onSave={()=>action('save')} busy={busy} dirty={dirty}/>:stage==='model'?<ModelPanel capabilities={cfg.capabilities} values={values} onChange={change} trace={trace} traceUrl={trace?modelAssetUrl(project,trace):undefined} onTrace={()=>action('trace')} busy={busy} canTrace={Boolean(bindings['train.manifest']||bindings['train.preparation'])} bindings={bindingPanel}/>:stage==='train'?<TrainingPanel capabilities={cfg.capabilities} values={values} onChange={change} onCheck={()=>action('check')} onSave={()=>action('save')} busy={busy}/>:stage==='execution'?<TrainingMonitor project={project} run={run} runs={runs} onRun={setRun} inputs={inputs} onInput={ref=>setBindings({'train.manifest':ref})} onStart={()=>action('execute')} busy={busy}/>:<PostWorkspace project={project} task={task} run={run} runs={runs} onRun={setRun} values={values} onChange={change} bindings={bindingPanel} onExecute={()=>action('execute')} busy={busy}/>}
 {stage!=='execution'&&stage!=='model'&&<ExecutionLog project={project} run={run}/>}</>
}
