import { ActionButton as Button } from "../../infrastructure/components/ActionButton";
import {Alert, Checkbox, Input, Modal, Select, Space, Table} from "antd";
import { useState } from 'react';
import { inspectFile } from '../previews';
/** 每条提取包含多个输出；输出成员独立保存身份与归属。 */
export function FieldExtractionEditor({project,task,root,files,entry,onSave,onCancel}:{project:string;task:string;root:string;files:string[];entry:any;onSave:(v:any)=>void;onCancel:()=>void}) {
 const [draft,setDraft]=useState<any>(structuredClone(entry)),[file,setFile]=useState<string>(),[fields,setFields]=useState<any[]>([]),[active,setActive]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const outputs=draft.outputs||[],output=outputs[active];
 function changeOutput(value:any){setDraft({...draft,outputs:outputs.map((o:any,i:number)=>i===active?value:o)})}
 async function read(){if(!file)return;setBusy(true);try{const split=file.indexOf("::"),sourceRoot=split<0?root:file.slice(0,split),sourcePath=split<0?file:file.slice(split+2);const info=await inspectFile(project,sourceRoot,sourcePath,task);setFields(info.fields||[]);setError('')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <Modal open title="字段提取" width={1100} onCancel={onCancel} okText="保存提取条目" onOk={()=>{if(!draft.name||!outputs.length||outputs.some((o:any)=>!o.name||!o.members.length)){setError('请填写名称并为每个输出选择至少一个字段');return}onSave(draft)}}><Input aria-label="提取名称" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><div className="extraction-grid"><section><h3>输入文件与字段</h3><Space><Select style={{width:300}} aria-label="读取文件" value={file} onChange={setFile} options={files.map(value=>({value,label:value}))}/><Button disabled={!file} loading={busy} onClick={read}>读取字段</Button></Space><Table rowKey="id" pagination={false} dataSource={fields} columns={[{title:'选择',render:(_,f)=><Checkbox disabled={!output} checked={output?.members.some((m:any)=>m.source_field===`${draft.source_selector}/${f.association}/${f.name}`)} onChange={e=>{const source_field=`${draft.source_selector}/${f.association}/${f.name}`;changeOutput({...output,members:e.target.checked?[...output.members,{source_field,output_member:f.name,components:f.components}]:output.members.filter((m:any)=>m.source_field!==source_field)})}}/>},{title:'字段',dataIndex:'name'},{title:'归属',dataIndex:'association'},{title:'形状',render:(_,f)=>JSON.stringify(f.shape)}]}/></section><section><h3>输出条目</h3><Select aria-label="数据域" value={draft.source_selector} options={['surface','volume'].map(value=>({value,label:value}))} onChange={value=>setDraft({...draft,source_selector:value})}/><Button onClick={()=>{setDraft({...draft,outputs:[...outputs,{id:crypto.randomUUID(),name:'output_'+(outputs.length+1),members:[]}]});setActive(outputs.length)}}>添加输出</Button>{outputs.map((o:any,i:number)=><div key={o.id} className="extraction-card" onClick={()=>setActive(i)} style={{borderColor:active===i?'#555':undefined}}><Input aria-label="输出名称" value={o.name} onChange={e=>setDraft({...draft,outputs:outputs.map((v:any,j:number)=>j===i?{...v,name:e.target.value}:v)})}/>{o.members.map((m:any,j:number)=><div key={m.source_field}><small>{m.source_field}</small><Input aria-label="输出成员名称" value={m.output_member} onChange={e=>{const next=structuredClone(draft);next.outputs[i].members[j].output_member=e.target.value;setDraft(next)}}/></div>)}<Button danger onClick={()=>{setDraft({...draft,outputs:outputs.filter((_:any,j:number)=>j!==i)});setActive(0)}}>删除输出</Button></div>)}</section></div>{error&&<Alert type="error" message={error}/>}</Modal>
}
