fluid:
  exp_name: CNO_double_cylinder_data_fluid
  gpu: 0
  seed: 0
  results_path: ./results/
  dataset_name: double_cylinder_data
  dataset_path: /path/to/gencp_dataset/
  num_workers: 12
  normalizer: range
  n_data_set: null
  length: 999
  dt: 10
  sdf_threshold: 0.04
  stage: fluid
  model_name: CNO
  use_torchcfm: true
  use_diffusion: false
  use_surrogate: false
  is_resume: false
  checkpoint_path: None
  input_size:
  - 128
  - 128
  in_dim: 4
  out_dim: 3
  in_channels: 4
  out_channels: 3
  in_size: 128
  depth: 4
  is_use_tb: true
  x0_is_use_noise: true
  test_interval: 1000
  train_batch_size: 4
  test_batch_size: 4
  input_step: 3
  output_step: 12
  stride: 1
  num_delta_t: 0
  lr: 0.0003
  sigma: 0.01
  train_mode: iteration
  total_iterations: 100000
  epochs: 1000
  scheduler: cosine
  T_max: 100000
  step_size: 50
  gamma: 0.5
  num_sampling_steps: 10
  save_figs_path: ./visualization_results
structure:
  exp_name: CNO_double_cylinder_data_structure
  gpu: 0
  seed: 0
  results_path: ./results/
  dataset_name: double_cylinder_data
  dataset_path: /path/to/gencp_dataset/
  num_workers: 12
  normalizer: range
  n_data_set: null
  length: 999
  dt: 10
  sdf_threshold: 0.04
  stage: structure
  model_name: CNO
  use_torchcfm: true
  use_diffusion: false
  use_surrogate: false
  is_resume: false
  checkpoint_path: None
  input_size:
  - 128
  - 128
  in_dim: 4
  out_dim: 1
  in_channels: 4
  out_channels: 1
  in_size: 128
  depth: 2
  is_use_tb: true
  x0_is_use_noise: true
  test_interval: 1000
  train_batch_size: 16
  test_batch_size: 16
  input_step: 3
  output_step: 12
  stride: 1
  num_delta_t: 0
  lr: 0.0003
  sigma: 0.01
  train_mode: iteration
  total_iterations: 100000
  epochs: 1000
  scheduler: cosine
  T_max: 100000
  step_size: 50
  gamma: 0.5
  num_sampling_steps: 10
  save_figs_path: ./visualization_results
