import {CaretRightOutlined, DownloadOutlined, InfoCircleFilled} from '@ant-design/icons';
import {Alert,Button,Drawer,Dropdown,Empty,Progress,Select,Space,Table,Tag} from 'antd';
import {useEffect,useMemo,useRef,useState} from 'react';
import {assetDownload} from '../files';
import {inferenceBatchLabel} from '../inference';
import {metricCatalog} from './api';
import {finished,jobLabel,type ResultCatalog} from './model';
import {usePostMetrics} from './usePostMetrics';
const sampleKey=(r:{sample:string;split?:string})=>JSON.stringify([r.split||"unknown",r.sample]);
const sampleLabel=(r:{sample:string;split?:string})=>`${({train:'训练集',eval:'评价集',validation:'评价集',test:'测试集'} as Record<string,string>)[r.split||'']||r.split||'历史分片'} · ${r.sample}`;
/** 固定结果评价面板。后处理页不再挂页签，组件与评价接口保留给程序或专项调用。 */
export function PostMetricsPanel({project,task,catalog,initialBatch,onExport,active=true}:{project:string;task:string;catalog:ResultCatalog;initialBatch?:string;onExport:()=>void;active?:boolean}){
 const [batches,setBatches]=useState<string[]>([]),[samples,setSamples]=useState<string[]>([]),[fields,setFields]=useState<string[]>([]),[metrics,setMetrics]=useState(['relative_l2','rmse','mse','mae']),[options,setOptions]=useState<any[]>([]),[selected,setSelected]=useState<React.Key[]>([]),[detail,setDetail]=useState<any>(),[query,setQuery]=useState(''),[catalogError,setCatalogError]=useState(''),[catalogRetry,setCatalogRetry]=useState(0);
 const [exportMenu,setExportMenu]=useState(false);
 useEffect(()=>{if(!active)setExportMenu(false);},[active]);
 const initial=useRef(false),model=usePostMetrics(project,task);
 useEffect(()=>{let active=true;metricCatalog(project,task).then(v=>{if(active){setOptions(Array.isArray(v?.metrics)?v.metrics:[]);setCatalogError('');}}).catch(e=>active&&setCatalogError(e.message));return()=>{active=false;};},[project,task,catalogRetry]);
 useEffect(()=>{if(initial.current||!catalog.items.length)return;initial.current=true;const latest=initialBatch||catalog.batches.find(b=>catalog.items.some(i=>i.batch_id===b.id))?.id||catalog.items[0].batch_id;setBatches([latest]);const items=catalog.items.filter(i=>i.batch_id===latest);setSamples([...new Set(items.map(sampleKey))]);setFields([...new Set(items.flatMap(i=>i.fields.filter(f=>f.default).map(f=>f.id)))]);},[catalog,initialBatch]);
 const available=catalog.items.filter(i=>batches.includes(i.batch_id)),sampleOptions=[...new Map(available.map(i=>[sampleKey(i),{value:sampleKey(i),label:sampleLabel(i)}])).values()];
 const inputs=available.filter(i=>samples.includes(sampleKey(i))&&i.evaluable),fieldOptions=useMemo(()=>Array.from(new Map(inputs.flatMap(i=>i.fields).map(f=>[f.id,f])).values()),[JSON.stringify(inputs)]);
 const request={results:inputs.map(i=>({id:i.id,revision:i.revision})),fields,metrics};
 const dirty=!!model.job&&JSON.stringify({...model.job.request,fields:model.job.request.fields.map((f:any)=>f.id),idempotency_key:undefined})!==JSON.stringify(request);
 const shown=(model.job?.rows||[]).filter(r=>[r.sample,r.field,r.domain,r.batch_id,r.checkpoint?.name].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase())));
 const rowMetrics=model.job?.request.metrics||metrics;
 const columns:any[]=[{title:'样本ID',dataIndex:'sample',fixed:'left',width:165,ellipsis:true,render:(v:string,r:any)=><button className="post-sample-link" title={sampleLabel(r)} onClick={()=>setDetail(r)}>{sampleLabel(r)}</button>},{title:'所属批次',dataIndex:'batch_id',width:140,ellipsis:true,render:(id:string)=>inferenceBatchLabel(catalog.batches.find(b=>b.id===id)||{id})},{title:'Checkpoint',dataIndex:'checkpoint',width:140,ellipsis:true,render:(c:any)=><span title={c?.revision}>{c?.name||'未记录'}{c?.epoch!=null&&` · epoch ${c.epoch}`}</span>},{title:'物理量',width:190,ellipsis:true,render:(_:any,r:any)=>`${r.domain} / ${r.field} · ${r.component==='magnitude'?'模长':r.component==='scalar'?'标量':r.component}`},...rowMetrics.map((key:string)=>({title:options.find(o=>o.id===key)?.label||key,key,width:98,sorter:(a:any,b:any)=>(a.values?.[key]??Infinity)-(b.values?.[key]??Infinity),render:(_:any,r:any)=><span title={r.undefined?.[key]}>{r.values?.[key]==null?'—':Number(r.values[key]).toPrecision(6)}</span>})),{title:'单位',dataIndex:'unit',width:70,render:(v:string)=>v||'未声明'},{title:'状态',dataIndex:'status',width:78,render:(v:string)=><Tag color={v==='failed'?'error':'success'}>{v==='failed'?'失败':'已计算'}</Tag>},{title:'计算时间',dataIndex:'calculated_at',width:155,render:(v:string)=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'—'},{title:'操作',fixed:'right',width:90,render:(_:any,r:any)=><Button type="link" onClick={()=>setDetail(r)}>查看详情</Button>}];
 async function download(format:string){const ids=selected.length?selected.map(String):shown.map(r=>r.id);const output=await model.download(format,ids);if(output){const a=document.createElement('a');a.href=assetDownload(project,output.ref);a.download=output.name;a.click();onExport();}}
 return <section className="post-metrics-panel"><div className="post-metric-config"><label>推理批次<Select getPopupContainer={trigger=>trigger.parentElement!} mode="multiple" aria-label="指标推理批次" value={batches} options={[...catalog.batches.map(b=>({value:b.id,label:inferenceBatchLabel(b)})),...catalog.items.filter(i=>i.batch_id.startsWith('legacy:')).map(i=>({value:i.batch_id,label:'历史 '+i.run_id.slice(0,8)}))]} onChange={ids=>{setBatches(ids);const next=catalog.items.filter(i=>ids.includes(i.batch_id));setSamples([...new Set(next.map(sampleKey))]);setFields([...new Set(next.flatMap(i=>i.fields.filter(f=>f.default).map(f=>f.id)))]);}} maxTagCount="responsive"/></label><label>样本<Select getPopupContainer={trigger=>trigger.parentElement!} mode="multiple" aria-label="指标样本" value={samples} options={sampleOptions} onChange={setSamples} maxTagCount={samples.length===sampleOptions.length?0:"responsive"} maxTagPlaceholder={omitted=>samples.length===sampleOptions.length?`全部样本 (${samples.length})`:`已选 ${omitted.length} 个样本`}/></label><label>物理量<Select getPopupContainer={trigger=>trigger.parentElement!} mode="multiple" aria-label="指标物理量" value={fields} options={fieldOptions.map(f=>({value:f.id,label:f.label}))} onChange={setFields} maxTagCount="responsive"/></label><label>指标配置<Select getPopupContainer={trigger=>trigger.parentElement!} mode="multiple" aria-label="指标配置" value={metrics} options={options.map(m=>({value:m.id,label:m.label}))} onChange={setMetrics} maxTagCount="responsive"/></label><Button aria-label="计算指标" icon={<CaretRightOutlined/>} type="primary" loading={model.busy} disabled={!inputs.length||!fields.length||!metrics.length||!!model.job&&!finished(model.job.status)} onClick={()=>{setSelected([]);void model.submit(request);}}>计算指标</Button><Dropdown trigger={["click"]} getPopupContainer={trigger=>trigger.closest(".post-metrics-panel") as HTMLElement} open={active&&exportMenu} onOpenChange={setExportMenu} menu={{items:[{key:'csv',label:'导出 CSV'},{key:'xlsx',label:'导出 Excel'},{key:'json',label:'导出 JSON'}],onClick:({key})=>{setExportMenu(false);void download(key);}}} disabled={!shown.length||model.busy||!model.job||!finished(model.job.status)}><Button aria-label="导出 ▾" icon={<DownloadOutlined/>}>导出 ▾</Button></Dropdown></div>
 {catalogError&&<Alert type="error" message={catalogError} action={<Button onClick={()=>setCatalogRetry(n=>n+1)}>重试指标目录</Button>}/>}
 {available.some(i=>!i.evaluable)&&<Alert type="warning" message="部分历史结果缺少可重算证据，可继续浏览文件" description={available.filter(i=>!i.evaluable).map(i=>`${i.sample}：${i.evaluation_error||'缺少字段、预测值或真值声明'}`).join('；')}/>}
 {model.job?.error&&<Alert type="error" message={model.job.error}/> }
 {model.error&&<Alert type="error" message={model.error} showIcon/>}
 <div className="post-metric-status"><InfoCircleFilled/><span>共选择 {inputs.length} 份样本结果 · {fields.length} 个物理量 · {metrics.length} 个指标 · 按检查点聚合</span><span>{model.job?`${jobLabel(model.job.status)} ${model.job.completed}/${model.job.total}`:'选择结果后计算'}{dirty?' · 配置已变化，待计算':''}</span><Select getPopupContainer={trigger=>trigger.parentElement!} aria-label="评价历史" placeholder="上次计算：尚无记录" value={model.job?.id} options={model.history.map(j=>({value:j.id,label:new Date(j.created_at).toLocaleString('zh-CN',{hour12:false})}))} onChange={id=>{setSelected([]);void model.open(id);}}/><input type="search" aria-label="筛选指标结果" placeholder="搜索样本或物理量" value={query} onChange={e=>{setQuery(e.target.value);setSelected([]);}}/></div>
 {model.job&&!finished(model.job.status)&&<Space><Progress percent={Math.round(model.job.completed/Math.max(1,model.job.total)*100)} style={{width:280}}/><Button onClick={model.cancel}>取消计算</Button></Space>}
 {model.job?.status==='partial'&&<Alert type="warning" message={`${model.job.failed} 项未完成，成功结果已保留，可在详情查看原因。`}/>}
 {new Set(shown.map(r=>r.protocol).filter(Boolean)).size>1&&<p className="post-protocol-note"><InfoCircleFilled/> 不同推理协议的结果并列展示，不进行综合排名。</p>}
 <Table bordered size="small" tableLayout="fixed" className="post-metric-table" rowKey="id" columns={columns} dataSource={shown} title={()=>'按检查点聚合'} rowSelection={{selectedRowKeys:selected,onChange:setSelected}} pagination={{defaultPageSize:10,showSizeChanger:true,showQuickJumper:true,showTotal:n=>`共 ${n} 条数据`}} scroll={{x:1450}} locale={{emptyText:<Empty description="选择批次、样本和物理量，计算后显示按检查点聚合的指标"/>}}/>
 <Drawer title="聚合指标详情" open={!!detail} onClose={()=>setDetail(undefined)} width={520}>{detail&&<><p>样本：{detail.sample}</p><p>来源运行：{detail.run_id}</p><p>物理量：{detail.domain} / {detail.field}</p><p>有效实体：{detail.count??'—'}；排除实体：{detail.excluded??'—'}</p><p>推理耗时：未记录；峰值显存：未记录</p>{detail.error&&<Alert type="error" message={detail.error}/>}<pre>{JSON.stringify({单位:detail.unit||'未声明',数值:detail.values,不可定义原因:detail.undefined,来源修订:detail.source_revision,协议:detail.protocol},null,2)}</pre></>}</Drawer>
 </section>;
}
