import {useEffect,useState} from 'react';
import {VisualizationWorkspace,PhysicalFilePreview,inspectAsset} from '../visualization';
/** 已登记文件统一检查后选择真实预览，外层弹窗由宿主拥有。 */
export function FilePreviewContent({asset,initialField,onError,scope,compact=false}:any){
 const [block,setBlock]=useState<string>(''),[info,setInfo]=useState<any>(null),[data,setData]=useState<any>(null),[field,setField]=useState(initialField||''),[offset,setOffset]=useState(0),[indices,setIndices]=useState<Record<string,number>>({}),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();setInfo(null);setError('');setData(null);setField(initialField||'');setOffset(0);setBlock('');inspectAsset(asset,'inspect',{},c.signal).then(setInfo).catch(e=>{if(!c.signal.aborted){setError(e.message);onError?.(e);}});return()=>c.abort();},[asset.asset_id,asset.revision]);
 useEffect(()=>{if(!info||info.kind==='mesh')return;const c=new AbortController();inspectAsset(asset,'read_slice',{field:field||undefined,offset,indices},c.signal).then(setData).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[info,field,offset,indices]);
 if(error)return <div role="alert">{error}</div>;if(!info)return <p role="status">读取文件…</p>;
 if(info.kind==='mesh')return <div className={compact?'compact-file-preview':undefined}>{info.blocks&&<label>数据块<select aria-label='数据块' value={block} onChange={e=>setBlock(e.target.value)}><option value=''>选择数据块</option>{info.blocks.map((b:any)=><option key={b.block} value={b.block}>块 {b.block} · {b.points} 点 · {b.dataset_type}</option>)}</select></label>}{(!info.blocks||block!=='')&&(compact?<PhysicalFilePreview source={{...asset,block:block||undefined}}/>:<VisualizationWorkspace scope={scope} sources={[{...asset,block:block||undefined}]} mode='preview' onError={onError}/>)}</div>;
 const current=info.fields?.find((f:any)=>f.name===field)||info.fields?.[0];
 return <div><select aria-label="预览成员" value={field} onChange={e=>{setField(e.target.value);setOffset(0);setIndices({});}}><option value="">默认成员</option>{info.fields?.map((f:any)=><option key={f.id||f.field_id} value={f.name}>{f.name}</option>)}</select>{current?.shape?.slice(2).map((size:number,i:number)=><label key={i}>维度 {i+2}<input type="number" min={0} max={size-1} value={indices[String(i+2)]||0} onChange={e=>setIndices({...indices,[String(i+2)]:+e.target.value})}/></label>)}<p>{JSON.stringify(data?.shape)} · {data?.dtype}</p>{data?.rows?<div style={{overflow:'auto',maxHeight:400}}><table><tbody>{data.rows.map((row:any[],i:number)=><tr key={i}>{row.map((v:any,j:number)=><td key={j}>{v===null?'非有限值':String(v)}</td>)}</tr>)}</tbody></table></div>:<pre>{data?.lines?.join('\n')}</pre>}<button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-100))}>上一页</button><button disabled={(data?.rows?.length||data?.lines?.length||0)<100} onClick={()=>setOffset(offset+100)}>下一页</button></div>;
}
