"""templates 功能模块；包级公开入口见 ai4e_task。"""

from .resources import (
    HelpIndexError,
    HelpSymbolNotFoundError,
    HelpTopicNotFoundError,
    check_example,
    copy_example,
    create_smoke_data,
    describe_help_symbol,
    export_guide,
    export_help,
    guide_info,
    help_info,
    help_root,
    list_examples,
    list_help_topics,
    read_case_manifest,
    read_help_topic,
    resource_root,
    search_help,
    source_location,
)

__all__ = [
    "HelpIndexError",
    "HelpSymbolNotFoundError",
    "HelpTopicNotFoundError",
    "check_example",
    "copy_example",
    "create_smoke_data",
    "describe_help_symbol",
    "export_guide",
    "export_help",
    "guide_info",
    "help_info",
    "help_root",
    "list_examples",
    "list_help_topics",
    "read_case_manifest",
    "read_help_topic",
    "resource_root",
    "search_help",
    "source_location",
]
