import { Button, Empty } from "antd";
import { FileExcelOutlined, FileTextOutlined } from "@ant-design/icons";
import type { useInferenceResults } from "./useInferenceResults";
import { splitLabel } from "./SamplePicker";
export const displayNumber=(n:number|null|undefined)=>n==null?"—":n!==0&&(Math.abs(n)<.001||Math.abs(n)>=100000)?n.toExponential(2):Number(n.toPrecision(5)).toString();
/** 样本等权统计表，未定义和未完成数量与固定结果一起展示。 */
export function InferenceMetricTable({view,onConfigure,onExport,exporting}:{view:ReturnType<typeof useInferenceResults>;onConfigure:()=>void;onExport:(format:string)=>void;exporting:boolean}) {
 return <section className="infer-card infer-metric-table" data-region="table"><header><h3>7. 指标表格</h3><span className="infer-summary">Checkpoint 对比查看　 |　{view.fields.find(f=>f.value===view.field)?.label||"待选择物理量"} · {view.metric||"待运行"}　 |　{splitLabel(view.split)}　 |　Mean / Median / P90 / Max</span><Button aria-label="导出 CSV" icon={<FileTextOutlined/>} disabled={!view.rows.length} loading={exporting} onClick={()=>onExport("csv")}>导出 CSV</Button><Button aria-label="导出 Excel" icon={<FileExcelOutlined/>} disabled={!view.rows.length} loading={exporting} onClick={()=>onExport("xlsx")}>导出 Excel</Button><Button aria-label="配置" onClick={onConfigure} disabled={!view.fields.length}>配置</Button></header>
 <div className="infer-table-scroll"><table className="infer-table"><thead><tr>{["Checkpoint","数据集","样本数","Mean","Median","P90","Max","推理耗时 (s)"].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{view.rows.map(r=><tr key={r.checkpoint_id+":"+r.split} title={`有效 ${r.valid} / 期望 ${r.expected}；不可定义 ${r.undefined}；${r.complete?"完整交付":"部分结果"}；${r.undefined_reasons?.join("；")||""}`}><td title={r.checkpoint_id}>{r.checkpoint}</td><td>{splitLabel(r.split)}</td><td>{r.valid}{r.valid!==r.expected?` / ${r.expected}`:""}{!r.complete?"（部分）":""}</td>{(["mean","median","p90","max"] as const).map(k=><td key={k}>{displayNumber(r[k])}{r[k]==null?<small>不可定义</small>:null}</td>)}<td>{displayNumber(r.prediction_seconds)}</td></tr>)}</tbody></table>{!view.rows.length&&<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="完成推理后显示真实指标；只评价也保留结果"/>}</div></section>;
}
