import { Button, Empty } from "antd";
import { FileExcelOutlined, FileTextOutlined } from "@ant-design/icons";
import type { useInferenceResults } from "./useInferenceResults";
import { splitLabel } from "./SamplePicker";
export const displayNumber=(n:number|null|undefined)=>n==null?"—":n!==0&&(Math.abs(n)<.001||Math.abs(n)>=100000)?n.toExponential(2):Number(n.toPrecision(5)).toString();
/** 行由模式确定，数值列由物理量、指标和聚合选择确定。 */
export function InferenceMetricTable({view,onConfigure,onExport,exporting}:{view:ReturnType<typeof useInferenceResults>;onConfigure:()=>void;onExport:(format:string)=>void;exporting:boolean}) {
 return <section className="infer-card infer-metric-table" data-region="table"><header><h3>指标表格</h3><span className="infer-summary">{view.config.mode==="checkpoint"?"Checkpoint 对比 · 全部样本聚合":`样本对比 · ${view.checkpoints.find(c=>c.value===view.config.checkpoint_id)?.label||"待选择 Checkpoint"}`}　|　{view.columns.length} 个指标字段</span><Button aria-label="导出 CSV" icon={<FileTextOutlined/>} disabled={!view.rows.length} loading={exporting} onClick={()=>onExport("csv")}>导出 CSV</Button><Button aria-label="导出 Excel" icon={<FileExcelOutlined/>} disabled={!view.rows.length} loading={exporting} onClick={()=>onExport("xlsx")}>导出 Excel</Button><Button aria-label="配置" onClick={onConfigure}>配置</Button></header>
 <div className="infer-table-scroll"><table className="infer-table" style={{minWidth:Math.max(600,(view.columns.length+2)*160)}}><thead><tr><th>{view.xLabel}</th><th>{view.config.mode==="checkpoint"?"样本数":"分片"}</th>{view.columns.map(c=><th key={c.id} title={c.label}>{c.label}</th>)}</tr></thead><tbody>{view.rows.map(r=><tr key={r.id}><td title={r.label}>{r.label}</td><td>{view.config.mode==="checkpoint"?r.count:splitLabel(r.split||"")}</td>{view.columns.map(c=><td key={c.id} title={r.reasons[c.id]}>{displayNumber(r.cells[c.id])}</td>)}</tr>)}</tbody></table>{!view.rows.length&&<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="完成推理后选择已有指标字段；只评价也保留结果"/>}</div></section>;
}
