import { ConfigProvider, Input, Layout } from 'antd';
import { MenuFoldOutlined, MenuUnfoldOutlined, SearchOutlined } from '@ant-design/icons';
import zhCN from 'antd/locale/zh_CN';
import { useEffect, useState } from 'react';
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { ErrorBoundary } from '../../infrastructure/components/ErrorBoundary';
import { ProjectNavigation, listProjects } from '../../modules/projects';
import { taskDetail } from '../../modules/tasks';
import { ProjectDetailPage } from '../pages/ProjectDetailPage';
import { TaskWorkbenchPage } from '../pages/TaskWorkbenchPage';
import { WorkbenchLandingPage } from '../pages/WorkbenchLandingPage';
function Shell(){
 const [collapsed,setCollapsed]=useState(false),[project,setProject]=useState<any>(),[task,setTask]=useState<any>();const location=useLocation(),nav=useNavigate();
 const parts=location.pathname.split('/'),p=parts[1]==='projects'?parts[2]:undefined,t=parts[3]==='tasks'?parts[4]:undefined;const inWorkbench=location.pathname==='/workbench'||!!t;
 useEffect(()=>{let live=true;if(!p){setProject(undefined);setTask(undefined);return()=>{live=false}}listProjects().then(rows=>{if(live)setProject(rows.find((r:any)=>r.id===p))}).catch(()=>{});if(!t){setTask(undefined);return()=>{live=false}}taskDetail(p,t).then(value=>{if(live)setTask(value)}).catch(()=>{});return()=>{live=false}},[p,t]);
 return <Layout className={'platform-shell '+(collapsed?'menu-collapsed':'')} style={{minHeight:'100vh'}}><Layout.Sider className="platform-sidenav" collapsed={collapsed} collapsedWidth={66} width={235} theme="light"><Link className="brand" to="/projects"><svg viewBox="0 0 30 34" width="31" height="36" aria-hidden="true"><path fill="#0071ff" d="m15 0 15 8.5v17L15 34V23l6-3.5v-8L15 8z"/><path fill="#53c8ff" d="M15 0 0 8.5 9 14l6-3.5 6 3.5 9-5.5z"/><path fill="#408efa" d="M0 8.5v17L15 34V23l-6-3.5V14z"/></svg>{!collapsed&&<b>Dojo WEB 平台</b>}</Link><button className="navtoggle" aria-label={collapsed?'展开菜单':'收起菜单'} onClick={()=>setCollapsed(!collapsed)}>{collapsed?<MenuUnfoldOutlined/>:<MenuFoldOutlined/>}{!collapsed&&<span>收起菜单</span>}</button><nav role="menu" aria-label="平台导航"><Link role="menuitem" aria-label="项目管理" className={'navitem '+(!inWorkbench?'selected':'')} aria-current={!inWorkbench?'page':undefined} to="/projects"><svg aria-hidden="true" viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" strokeWidth="1.7"><path d="M3 7V5h7l2 2h9v13H3z"/><path d="M3 9h18"/></svg>{!collapsed&&<span>项目管理</span>}</Link><Link role="menuitem" aria-label="任务工作台" className={'navitem '+(inWorkbench?'selected':'')} aria-current={inWorkbench?'page':undefined} to="/workbench"><svg aria-hidden="true" viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" strokeWidth="1.7"><rect x="4" y="3" width="16" height="18" rx="2"/><path d="m7 12 3 3 7-7"/></svg>{!collapsed&&<span>任务工作台</span>}</Link></nav>{!collapsed&&<div className="sidebar-footer"><div className="sidebar-mountain"/><p>用计算加速科学发现<small>Do More with AI</small></p></div>}</Layout.Sider><Layout><Layout.Header><nav className="header-breadcrumb" aria-label="当前位置"><Link to="/projects">项目导航</Link>{p&&<> / <Link to={`/projects/${p}/tasks`}>{project?.name||'正在读取项目'}</Link></>}{t&&<> / <span>{task?.name||'正在读取任务'}</span> / <span>任务工作台</span></>}{location.pathname==='/workbench'&&<> / <span>任务工作台</span></>}</nav><div className="header-tools"><Input className="globalfind" aria-label="全局搜索" prefix={<SearchOutlined/>} placeholder="搜索项目名称、任务名称或关键词…" onPressEnter={e=>nav('/workbench?q='+encodeURIComponent(e.currentTarget.value))}/><span className="local-mode">本机研究</span><span className="local-account"><i>研</i> 本机用户　⌄</span></div></Layout.Header><Layout.Content><Routes><Route path="/workbench" element={<WorkbenchLandingPage/>}/><Route path="/projects" element={<ProjectNavigation/>}/><Route path="/projects/:p/tasks/:t/:step" element={<TaskWorkbenchPage/>}/><Route path="/projects/:p/:tab" element={<ProjectDetailPage/>}/><Route path="*" element={<Navigate to="/projects" replace/>}/></Routes></Layout.Content></Layout></Layout>
}
/** 路由感知外壳保留原型两个一级入口；真实任务由工作台选择器进入。 */
export function PlatformLayout(){return <ConfigProvider locale={zhCN} theme={{token:{colorPrimary:'#0873ff',borderRadius:6,fontSize:13,colorBgLayout:'#f5faff'}}}><ErrorBoundary><BrowserRouter><Shell/></BrowserRouter></ErrorBoundary></ConfigProvider>}
