import { ActionButton as Button } from "../../infrastructure/components/ActionButton";
import {Card, Checkbox} from "antd";
import { ConfigurationField } from '../../infrastructure/components/ConfigurationField';
import './training.css';
const labels:Record<string,string>={validation_interval:'验证间隔',parameter_group_policy:'参数分组策略',scheduler_unit:'调度更新单位',min_lr_ratio:'最小学习率比例',snapshot:'保存代码快照',log_every_updates:'更新日志间隔',optimizer:'优化器',learning_rate:'学习率',weight_decay:'权重衰减',precision:'训练精度',accumulate:'梯度累积',gradient_clip:'梯度裁剪',scheduler:'学习率调度',warmup_ratio:'预热比例',min_lr:'最小学习率',max_epochs:'训练轮数',batch_size:'批次大小',device:'执行设备',num_workers:'数据加载进程',ema_decay:'EMA 衰减',ema_save_every:'EMA 保存周期',log_every:'日志轮次间隔',test_repeat:'测试重复次数',evaluation_split:'测试分片',evaluation_enabled:'启用测试评估',save_on_interrupt:'中断保存检查点'};
/** 训练设置按优化、控制、EMA、诊断及测试分组，只呈现已有配置能力。 */
export function TrainingPanel({capabilities,values,onChange,onCheck,onSave,busy}:{capabilities?:any;values:any;onChange:(key:string,v:any)=>void;onCheck:()=>void;onSave:()=>void;busy:boolean}){
 const fields=(keys:string[])=>keys.filter(k=>k in values).map(key=><ConfigurationField key={key} label={labels[key]||key} help={"train."+key} value={values[key]} options={capabilities?.training_options?.[key]} disabled={capabilities?.training_constraints?.[key]?.readOnly || (['optimizer','precision','device','scheduler','scheduler_unit','parameter_group_policy','evaluation_split'].includes(key) && !capabilities?.training_options?.[key])} onChange={v=>onChange(key,v)}/>);
 return <div className="training-layout"><Card title="训练参数设置" className="training-left"><h3>参数优化</h3><div className="configuration-grid">{fields(['optimizer','learning_rate','weight_decay','precision','accumulate','gradient_clip','scheduler','scheduler_unit','warmup_ratio','min_lr','min_lr_ratio'])}</div><h3>训练控制</h3><div className="configuration-grid">{fields(['max_epochs','batch_size','device','num_workers','save_on_interrupt','parameter_group_policy'])}</div><h3>维护 EMA 权重</h3><Checkbox checked={values.ema_decay!==null&&values.ema_decay!==undefined} onChange={e=>onChange('ema_decay',e.target.checked?.9999:null)}>启用 EMA</Checkbox><div className="configuration-grid">{fields(['ema_decay','ema_save_every'])}</div></Card><div className="training-right"><Card title="默认训练诊断"><div className="configuration-grid">{fields(['log_every','log_every_updates','snapshot'])}</div><div className="diagnostic-options"><Checkbox checked disabled>运行日志</Checkbox><Checkbox checked={values.snapshot===true} disabled={!("snapshot"in values)} onChange={e=>onChange("snapshot",e.target.checked)}>代码快照</Checkbox><Checkbox disabled>梯度直方图（当前案例未声明）</Checkbox><Checkbox disabled>性能剖析（当前案例未声明）</Checkbox></div><p>日志间隔按当前案例实际支持项保存；未声明诊断不可提交。</p></Card><Card title="测试评估"><div className="configuration-grid">{fields(['evaluation_enabled','evaluation_split','validation_interval','test_repeat','evaluate_repeat'])}</div><p>测试损失和物理指标由模型学习目标和既有评价能力提供。</p></Card><Card title="训练配置检查"><p>准备记录、模型采样和输入字段在检查时共同核验。</p><Button loading={busy} onClick={onCheck}>预检</Button> <Button type="primary" loading={busy} onClick={onSave}>保存训练设置</Button></Card></div></div>
}
