import {test,expect} from '@playwright/test';
/** 固定创建参数经应用协调加入比较，打开已保存比较后重新保存不漂移。 */
test('版本分阶段参数加入比较与保存选择恢复',async({page,request})=>{
 const api=(process.env.DOJO_API_URL||'http://127.0.0.1:8002')+'/api/v1';const p=await(await request.post(api+'/projects',{data:{name:'研究记录浏览器 '+Date.now()}})).json();const a=await(await request.post(`${api}/projects/${p.id}/tasks`,{data:{name:'研究记录A'}})).json();const configuration=await(await request.get(`${api}/projects/${p.id}/tasks/${a.id}/configuration`)).json();await request.put(`${api}/projects/${p.id}/tasks/${a.id}/configuration`,{data:{stage:'train',expected_revision:configuration.revision,values:{max_epochs:3}}});const b=await(await request.post(`${api}/projects/${p.id}/tasks/${a.id}/fork`,{data:{name:'研究记录B'}})).json();
 await page.goto(`/projects/${p.id}/lineage`);for(const task of [a,b]){if(task===b){await page.getByRole('tab',{name:'版本树',exact:true}).click();}await page.getByRole('button',{name:'选择任务 '+task.version_id,exact:true}).click();await expect(page.getByText(/参数来源：创建快照/)).toBeVisible();await page.getByLabel('血缘任务阶段').selectOption({label:'5. 训练设置'});await page.getByRole('tab',{name:'参数',exact:true}).click();await page.getByRole('row').filter({has:page.getByRole('cell',{name:'max_epochs',exact:true})}).getByRole('button',{name:'加入比较',exact:true}).click();await expect(page.getByText(/已加入比较参数：train.max_epochs/)).toBeVisible();}
 await page.getByRole('button',{name:/^比\s*较$/}).click();await expect(page.getByRole('cell',{name:'train.max_epochs',exact:true})).toBeVisible();const firstSave=page.waitForResponse(r=>r.url().endsWith('/comparisons')&&r.request().method()==='POST');await page.getByRole('button',{name:'保存固定比较',exact:true}).click();expect((await firstSave).ok()).toBeTruthy();
 const saved=await(await request.get(`${api}/projects/${p.id}/comparisons`)).json();expect(saved).toHaveLength(1);await page.locator('.ant-select').first().click();await page.locator('.ant-select-item-option').filter({hasText:'当前工作目录'}).click();await page.locator('.ant-select').last().click();await page.locator('.ant-select-item-option').filter({hasText:saved[0].created_at}).click();const posted=page.waitForRequest(r=>r.url().endsWith('/comparisons')&&r.method()==='POST');await page.getByRole('button',{name:'保存固定比较',exact:true}).click();expect((await posted).postDataJSON()).toMatchObject(saved[0].selection);
 let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);let requested!:()=>void;const started=new Promise<void>(resolve=>requested=resolve);
 await page.route('**/api/v1/projects/'+p.id+'/compare',async route=>{const response=await route.fetch();requested();await gate;await route.fulfill({response})});await page.getByRole('button',{name:/^比\s*较$/}).click();await started;await expect(page.getByRole('button',{name:'保存固定比较',exact:true})).toBeDisabled();await page.locator('.ant-select').first().click();await page.locator('.ant-select-item-option').filter({hasText:'当前工作目录'}).click();const returned=page.waitForResponse(r=>r.url().endsWith('/compare'));release();await returned;await page.waitForTimeout(100);await expect(page.getByRole('button',{name:'保存固定比较',exact:true})).toBeDisabled();await expect(page.getByRole('cell',{name:'train.max_epochs',exact:true})).toHaveCount(0);

});
