import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
/** 正式 post 导出的网格，固定资产来源，不复制或重新登记文件。 */
test('真实 HTTP NASA 导出网格字段及原始身份',async({page},testInfo)=>{
 const evidence=JSON.parse(readFileSync(process.env.DOJO_MESH_EVIDENCE||resolve('../../.context/mvp/web-integrated-results/nasa_crm_transolver3-preview.json'),'utf8')),asset=evidence.mesh;
 let display:any=null;const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',async response=>{if((response.url().includes('/operations/')||response.url().endsWith('/visualization/operations'))&&['GET','POST'].includes(response.request().method())){try{const record=await response.json();if(record.status==='succeeded'&&record.result?.geometry_buffers)display={...record.result,display_ref:record.result_refs[0]};}catch{}}});
 await page.goto('/projects');await page.evaluate(async asset=>{const React=await import('/node_modules/.vite/deps/react.js' as any),ReactDOM=await import('/node_modules/.vite/deps/react-dom_client.js' as any),{VisualizationWorkspace}=await import('/src/modules/visualization/index.ts' as any);const host=document.createElement('div');document.body.replaceChildren(host);(window as any).__exportRoot=(ReactDOM.createRoot||ReactDOM.default.createRoot)(host);(window as any).__exportRoot.render((React.createElement||React.default.createElement)(VisualizationWorkspace,{sources:[{...asset,name:'NASA Transolver3 正式导出表面'}],onInspectEntity:(p:any)=>{(window as any).__exportPick=p;}}));},asset);
 await expect(page.getByRole('status')).toHaveCount(0,{timeout:120000});await expect(page.getByRole('alert')).toHaveCount(0);await expect(page.locator('.viz-canvas canvas')).toHaveCount(1);await expect.poll(()=>display).not.toBeNull();
 expect(display.geometry_buffers[0].shape).toEqual([454404,3]);expect(display.topology_buffers.some((b:any)=>b.name==='polys')).toBe(true);expect(display.entity_mapping.generated_entities).toBe(false);
 expect(display.fields.map((f:any)=>f.field_id)).toEqual(expect.arrayContaining(['point:surface.cp.prediction','point:surface.cp.truth','point:original_point_id','cell:original_cell_id']));
 const identity=await page.evaluate(async({display,asset})=>{const {decodeBuffer}=await import('/src/infrastructure/assets/binary.ts' as any),{bufferUrl}=await import('/src/modules/visualization/api.ts' as any);const mapping=display.entity_mapping.point,original=display.fields.find((f:any)=>f.field_id==='point:original_point_id').buffer;const read=async(d:any)=>decodeBuffer(await (await fetch(bufferUrl(asset,display.display_ref,d.path))).arrayBuffer(),d);const [a,b]=await Promise.all([read(mapping),read(original)]);return {rows:a.length,equal:a.length===b.length&&Array.from(a).every((v:any,i:number)=>String(v)===String(b[i]))};},{display,asset});expect(identity).toEqual({rows:454404,equal:true});
 await page.getByLabel('显示字段').selectOption('point:surface.cp.prediction');await page.waitForTimeout(400);const box=await page.locator('.viz-canvas').boundingBox();if(!box)throw new Error('missing canvas');await page.mouse.click(box.x+box.width/2,box.y+box.height/2);await expect.poll(()=>page.evaluate(()=>(window as any).__exportPick)).toMatchObject({association:'point',generated:false});const picked=await page.evaluate(()=>(window as any).__exportPick);expect(picked.original_id).not.toBeNull();expect(picked.values).toHaveLength(1);expect(Number.isFinite(Number(picked.values[0]))).toBe(true);
 const png=await page.locator('.viz-canvas').screenshot({path:testInfo.outputPath('nasa-export.png')});await testInfo.attach('正式NASA预测表面',{body:png,contentType:'image/png'});expect(errors).toEqual([]);await page.evaluate(()=>(window as any).__exportRoot.unmount());
});
