import {test,expect} from '@playwright/test';
/** 坐标声明与恢复的明确契约夹具；实际VTK证据生产由Python测试覆盖。 */
test('相机完整来源、跨源证据及场景恢复校验',async({page})=>{
 const a={project_id:'camera-fixture',asset_id:'a',revision:'v1',member:'mesh',block:'0'},b={...a,asset_id:'b'};let legal=true;
 const descriptor={name:'points',path:'points',dtype:'float32',shape:[3,3],byte_length:36,byte_order:'little'};
 await page.route('**/api/v1/projects/camera-fixture/**',async route=>{const req=route.request();if(req.url().includes('/content?'))return route.fulfill({contentType:'application/octet-stream',body:Buffer.from(new Float32Array([-1,-1,0,1,-1,0,0,1,0]).buffer)});if(req.url().endsWith('/visualization/operations')){const source=req.postDataJSON().source;return route.fulfill({json:{operation_id:source.asset_id,status:'succeeded',result_refs:[{...source,asset_id:'display-'+source.asset_id}],result:{schema_version:1,geometry_buffers:[descriptor],topology_buffers:[],fields:[],entity_mapping:{generated_entities:false},coordinate_space:legal?{id:'explicit-body-frame',unit:'m',evidence:'source-declaration',source_refs:[source]}:undefined}}});}return route.fulfill({json:{status:'canceled'}});});
 await page.goto('/projects');
 const semantics=await page.evaluate(async({a,b})=>{const {sameCoordinateSource,cameraSourcesCompatible,cameraLinkUnitNotice}=await import('/src/modules/visualization/model.ts' as any);const proof=(s:any,id='frame',unit='m')=>({coordinate_space:{id,unit,evidence:'source-declaration',source_refs:[s]}});return {same:sameCoordinateSource(a,{...a}),changed:['project_id','asset_id','revision','member','block'].map(key=>sameCoordinateSource(a,{...a,[key]:'changed'})),known:cameraSourcesCompatible(a,b,proof(a),proof(b)),unknown:cameraSourcesCompatible(a,b),unit:cameraSourcesCompatible(a,b,proof(a),proof(b,'frame','mm')),stale:cameraSourcesCompatible(a,b,proof({...a,revision:'old'}),proof(b)),foreign:cameraSourcesCompatible(a,b,proof(b),proof(a)),space:cameraSourcesCompatible(a,b,proof(a),proof(b,'other')),unitNotice:cameraLinkUnitNotice(a,b,proof(a),proof(b,'frame','mm')),spaceNotice:cameraLinkUnitNotice(a,b,proof(a),proof(b,'other'))};},{a,b});expect(semantics).toEqual({same:true,changed:[false,false,false,false,false],known:true,unknown:true,unit:true,stale:true,foreign:true,space:true,unitNotice:'相机已联动；来源单位不一致：m、mm',spaceNotice:''});
 await page.evaluate(async({a,b})=>{const React=await import('/node_modules/.vite/deps/react.js' as any),ReactDOM=await import('/node_modules/.vite/deps/react-dom_client.js' as any),{VisualizationWorkspace}=await import('/src/modules/visualization/index.ts' as any);(window as any).__mountCamera=()=>{(window as any).__cameraRoot?.unmount();const host=document.createElement('div');document.body.replaceChildren(host);(window as any).__cameraRoot=(ReactDOM.createRoot||ReactDOM.default.createRoot)(host);(window as any).__cameraRoot.render((React.createElement||React.default.createElement)(VisualizationWorkspace,{sources:[a,b],scene:{schema_version:1,sources:[a,b],pipeline_nodes:[],representations:[],viewports:[{id:'left',source:0},{id:'right',source:1}],link_groups:[{id:'camera',kind:'camera',enabled:true,view_ids:['left','right']}],active_view:'left',selected_node:null},onSceneChange:(s:any)=>{(window as any).__cameraSaved=s;}}));};(window as any).__mountCamera();},{a,b});
 await expect(page.getByRole('status')).toHaveCount(0);await expect(page.getByLabel('相机联动',{exact:true})).toBeChecked();await expect(page.locator('.viz-canvas canvas')).toHaveCount(2);
 legal=false;await page.evaluate(()=>(window as any).__mountCamera());await expect(page.getByRole('status')).toHaveCount(0);await expect(page.getByLabel('相机联动',{exact:true})).toBeChecked();await expect(page.getByLabel('相机联动说明')).toHaveCount(0);await page.getByRole('button',{name:'保存场景'}).click();expect((await page.evaluate(()=>(window as any).__cameraSaved)).link_groups).toEqual([{id:'camera',kind:'camera',enabled:true,view_ids:['left','right']}]);
 await page.getByLabel('相机联动',{exact:true}).click();await expect(page.getByLabel('相机联动',{exact:true})).not.toBeChecked();await page.evaluate(()=>(window as any).__cameraRoot.unmount());
});

test('真实服务显式坐标夹具允许联动而NASA未知声明恢复断开',async({page,request})=>{
 const {readFileSync}=await import('node:fs'),{resolve}=await import('node:path');const api=process.env.DOJO_API_URL||'http://127.0.0.1:8002';
 const created=await request.post(api+'/api/v1/projects',{data:{name:'显式坐标契约测试夹具 '+Date.now()}});expect(created.ok()).toBe(true);const project=(await created.json()).id;const sources=[];
 for(const side of ['left','right']){const result=await request.post(`${api}/api/v1/projects/${project}/assets`,{data:{root:'data0',path:`viz-camera-contract/${side}.vtp`}});expect(result.ok()).toBe(true);sources.push(await result.json());}
 await page.goto('/projects');await page.evaluate(async sources=>{const React=await import('/node_modules/.vite/deps/react.js' as any),ReactDOM=await import('/node_modules/.vite/deps/react-dom_client.js' as any),{VisualizationWorkspace}=await import('/src/modules/visualization/index.ts' as any);(window as any).__mountRealCamera=(sources:any[])=>{(window as any).__realCameraRoot?.unmount();const host=document.createElement('div');document.body.replaceChildren(host);(window as any).__realCameraRoot=(ReactDOM.createRoot||ReactDOM.default.createRoot)(host);(window as any).__realCameraRoot.render((React.createElement||React.default.createElement)(VisualizationWorkspace,{sources,scene:{schema_version:1,sources,pipeline_nodes:[],representations:[],viewports:[{id:'left',source:0},{id:'right',source:1}],link_groups:[{id:'camera',kind:'camera',enabled:true,view_ids:['left','right']}],active_view:'left',selected_node:null},onSceneChange:(scene:any)=>{(window as any).__realCameraSaved=scene;}}));};(window as any).__mountRealCamera(sources);},sources);
 await expect(page.getByRole('status')).toHaveCount(0,{timeout:120000});await expect(page.getByRole('alert')).toHaveCount(0);await expect(page.getByLabel('相机联动',{exact:true})).toBeChecked();await expect(page.locator('.viz-canvas canvas')).toHaveCount(2);const box=await page.locator('.viz-canvas').first().boundingBox();if(!box)throw new Error('missing canvas');await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+30,box.y+box.height/2+20,{steps:5});await page.mouse.up();await page.getByRole('button',{name:'保存场景'}).click();const linked=await page.evaluate(()=>(window as any).__realCameraSaved);expect(linked.viewports[0].camera.position).toEqual(linked.viewports[1].camera.position);
 const mesh=JSON.parse(readFileSync(resolve('../../.context/mvp/web-integrated-results/nasa_crm_transolver3-preview.json'),'utf8')).mesh,difference=JSON.parse(readFileSync(resolve('../../.context/mvp/web-integrated-results/nasa-http-difference.json'),'utf8')).operation.result_refs[0];await page.evaluate(sources=>(window as any).__mountRealCamera(sources),[mesh,difference]);
 await expect(page.getByRole('status')).toHaveCount(0,{timeout:120000});await expect(page.getByRole('alert')).toHaveCount(0);await expect(page.locator('.viz-canvas canvas')).toHaveCount(2);await expect(page.getByLabel('相机联动',{exact:true})).toBeChecked();await page.getByRole('button',{name:'保存场景'}).click();expect((await page.evaluate(()=>(window as any).__realCameraSaved)).link_groups).toEqual([{id:'camera',kind:'camera',enabled:true,view_ids:['left','right']}]);await page.evaluate(()=>(window as any).__realCameraRoot.unmount());
});
